engines:
  eslint:
    enabled: true
    checks:
      import/extensions:
        enabled: false
      file-lines:
        config:
          threshold: 300
      method-lines:
        enabled: false
  duplication:
    enabled: false
    config:
      languages:
      - javascript
ratings:
  paths:
  - "**.js"
exclude_paths:
- server/tests/
- server/migrations/
- server/seeders/
- client/tests/
- client/e2eTest/