const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
const SET_CURRENT_USER = 'SET_CURRENT_USER';
const UNSET_CURRENT_USER = 'UNSET_CURRENT_USER';

export {
  ADD_FLASH_MESSAGE,
  DELETE_FLASH_MESSAGE,
  SET_CURRENT_USER,
  UNSET_CURRENT_USER,
};
